/*
 * GENERATED by tools/mono-font-gen.py - do not edit.
 * Source: FontTiny (RLE, 7px, U+0020..U+0023)
 */

#include "FontTiny.h"

namespace {

const uint8_t fontData[] = {
    0xFE, 0x0D, 0x06, 0x22, 0x42, 0x42, 0x42, 0x42, 0x26, 0x0F, 0xE0, 0xD0, 0x14, 0x11, 0x42, 0x42, 
    0x42, 0x42, 0x41, 0x14, 0x10, 
};

const uint8_t fontWidths[] = {
    6, 6, 6, 6, 
};

const uint16_t fontOffsets[] = {
    0, 2, 9, 12, 
};

}

const Font FontTiny = {
    .height = 7,
    .spacing = 0,
    .fixedWidth = 0,
    .missingWidth = 6,
    .firstChar = 0x20,
    .charCount = 4,
    .widths = fontWidths,
    .offsets = fontOffsets,
    .data = fontData,
    .format = FontFormat::RLE,
};
